title: FullBeans! Radio
email: hartgeld@pm.me
description: >- 
  Independent community radio station focusing on local artists.
baseurl: "" 
url: "https://radio.holgerardelt.de/" 
host: localhost
# github_username: hartgeld

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-responsive-image
#  - jekyll-auto-image

include:
  - "_pages"
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/bundle/ruby
  - .git
  - _site

assets:
   sources:
     - img
     - img/uploads
     - assets

collections:
  shows:
    output: true

feed:
  collections:
    - all

rss: "RSS Feed"

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 90
  sizes:
    - width: 480
      quality: 80
    - width: 800
    - width: 1400
      quality: 90
  auto_rotate: false
  strip: true
  base_path: img
  output_path_format: assets/resized/%{width}/%{basename}
  save_to_source: false
  cache: false
  extra_images:
    - img/*.{jpeg,jpg}