title: radio
email: hartgeld@pm.me
description: >- 
  An independently operating community radio station based in Stuttgart, focusing on local artists.
baseurl: "" 
url: "" 
github_username: hartgeld

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - "_pages"
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/bundle/ruby
  - .git
  - _site