backend:
  name: github
  repo: hartgeld/radio
  branch: master

media_folder: "img"

collections:
  - name: "shows"
    label: "Show"
    folder: "_shows"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "show"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "file"}
      - {label: "MP3 URL", name: "mp3Url", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"} 